#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#export MAVEN_OPTS="-Xms1024m -Xmx2048m"
#export GOROOT=$HOME/go1.7
export GOPATH=~/dev/go
export PATH=~/bin:$GOPATH/bin:/opt/apache-maven/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:$PATH:/usr/local/sbin:$GOROOT/bin
export DEFAULT_USER=rpit

export JAVA_HOME=$(/usr/libexec/java_home -v 11)

export LC_CTYPE="en_US.utf-8"

# jq helper for service.log
alias jqs='grep --line-buffered "^{.*}$" | jq --unbuffered -r '\''[."@timestamp", .level, "["+.thread_name+"]", .logger_name+":", .message, .stack_trace] | join(" ")'\'''
# jq helper for request.log
alias jqr='grep --line-buffered "^{.*}$" | jq --unbuffered -r '"'"'["["+."@timestamp"+"]", .remoteHost, "\""+.requestedUrl+"\"", .host, (.statusCode|tostring), "["+(.contentLength|tostring)+" b]", "["+(.elapsedTime|tostring)+" ms]", "-", "\""+.userAgent+"\"" ] | join(" ")'"'"''

# Docker
alias dm='docker-machine'
alias aq='docker rm -fv $(docker ps -aq)'
alias dl='docker ps -lq'
alias dang='docker rmi $(docker images -f "dangling=true" -q)'
alias prune='docker system prune -f'
alias dc='docker-compose'

# Git
alias gs='git status -sb'
alias gd='git diff'
alias gdc='git diff --cached'
alias ga='(gr && git add .)'
alias gca='git commit --amend'
alias gu='git up'
alias g-='git checkout -'
alias gm='git checkout master'
alias gco='git checkout'
alias gc='git commit'
alias gl='git log -1 --stat'
alias gb='git branch'
alias gcb='f() { git checkout -b ${1} && git branch --set-upstream-to=origin/master };f'
alias gwip='ga && git commit -m"autoWIP"'
alias gr='cd $(git rev-parse --show-toplevel)'
alias gsu='git submodule update --init --recursive'

alias tf='terraform'
alias vi='nvim'
alias vim='nvim'

alias c='code .'
alias z='fasd_cd'
alias cat='ccat --bg=light'
alias ls='ls -lAsGhF'
alias grep='grep --color'
alias hist='history -150'

# Nomad
alias n='nomad'
alias ns='nomad status'
alias nas='nomad alloc-status'
alias nss='nomad node-status'
alias nsm='nomad server-members'
alias nfs='nomad fs'
alias nl='nomad logs -f'

unsetopt histverify

source ~/.zshrc_ebay

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

eval $(thefuck --alias fu)


autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/nomad nomad
